#include <stdio.h>

// while loop: Checks the conditions and then executes the code...
// do-while loop: First executes the code and then checks the conditons...

int main(){
    int i = 20;
 do{
     printf("The value of i is %d\n", i);   // do-while loop executes at least 1 time...
                                            // Or  1 Baar toh krega hi krega...
     i++;
 }
 while(i < 10);        //  Always use semicolon ';' after while() in do while loop...
    return 0;
}         