#include <stdio.h>
// Pointer is a variable which stores the adress of other variables...
int main()
{
    int i =1;
    int *j; // int * is used to declare pointer... // Now j is a pointer...
    j = &i; // now j stores the address of i...

    // & = address of operator...
    // This operator is used to obtain the adress of given variale...
    //  In Simple Words:- It gives address...

    // * = Value of address operator...
    // This operator is used to obtain the value of present at the given memory...
    //  In Simple Words:- It gives value...

    printf("The value of i is %d\n", i); 

    printf("The value of i is %d\n", *j); // * operator gives us value...
    
    printf("The value of i is %d\n",*(&i)); // finding value using address...
 
    printf("The adress of i is %u\n", &i);  // & is used to obtain the address of operator...

    printf("The adress of i is %u\n", j);   // %u is format specifier to print pointer adress...

    printf("The adress of j is %u\n", &j);  // &j is used to find to find the address of j...

    printf("The value of j is %u\n", *(&j)); // *(&j) is used to find the value from address...
    return 0;
}